name: Atlas CFN Resource Publish
on:
  workflow_dispatch:
    inputs:
      regions:
        description: "comma seperated AWS regions"
        default: "us-east-1"
        required: true
      resourceNames:
        description: "the folder name of the Resource in this Repo"
        default: "custom-db-role"
        required: true
jobs:
  publish-mongodb-atlas-resource:
    name: publish-mongodb-atlas-resource
    runs-on: ubuntu-20.04
    env:
      RESOURCE_NAMES: ${{ github.event.inputs.resourceNames }}
      OTHER_PARAMS: ${{ github.event.inputs.otherParams }}
      REGIONS: ${{ github.event.inputs.regions }}
      ATLAS_PUBLIC_KEY: ${{ secrets.ATLAS_PUBLIC_KEY }}
      ATLAS_PRIVATE_KEY: ${{ secrets.ATLAS_PRIVATE_KEY }}
      ATLAS_ORG_ID: ${{ secrets.ATLAS_ORG_ID }}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run publishing script
        run: |
          pwd
          cd ./.github/scripts
          chmod +x cfn-publish.sh
          ./cfn-publish.sh

