name: Atlas CFN Resource Publish
on:
  workflow_dispatch:
    inputs:
      regions:
        description: "comma seperated AWS regions"
        default: "us-east-1,us-west-1"
        required: true
      resourceNames:
        description: "the folder name of the Resource in this Repo"
        default: "custom-db-role,maintenance-window"
        required: true
jobs:
  publish-mongodb-atlas-resource:
    name: publish-mongodb-atlas-resource
    runs-on: ubuntu-20.04
    env:
      RESOURCES: ${{ github.event.inputs.resourceNames }}
      OTHER_PARAMS: ${{ github.event.inputs.otherParams }}
      REGIONS: ${{ github.event.inputs.regions }}
      ATLAS_PUBLIC_KEY: ${{ secrets.ATLAS_PUBLIC_KEY }}
      ATLAS_PRIVATE_KEY: ${{ secrets.ATLAS_PRIVATE_KEY }}
      ATLAS_ORG_ID: ${{ secrets.ATLAS_ORG_ID }}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup Atlas CLI
        uses: andreaangiolillo/atlas-cli-github-action@main
        with:
          public-key: ${{ secrets.ATLAS_PUBLIC_KEY }}
          private-key: ${{ secrets.ATLAS_PRIVATE_KEY }}
          org-id: ${{ secrets.ATLAS_ORG_ID }}
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli
          aws --version
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install cloudformation-cli cloudformation-cli-go-plugin
      - name: Run publishing script
        run: |
          pwd
          chmod +x cfn-global-publish.sh
          ./cfn-global-publish.sh $REGIONS $RESOURCES $OTHER_PARAMS

